# -*- coding: utf-8 -*-
"""13_Feb_sklearn_multisat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/108cWhcx4cN3nK36hYgmB3sLaCtxFEzGP
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')

dataset = pd.read_csv('multisat.csv')

dataset

plt.scatter(dataset['SAT'],dataset['GPA'])
plt.xlabel('SAT----independent')
plt.ylabel('GPA-----dependent')
plt.show()

plt.scatter(dataset['Rand 1,2,3'],dataset['GPA'])
plt.xlabel('Rand 1,2,3----independent')
plt.ylabel('GPA-----dependent')
plt.show()

X = dataset.iloc[:,[0,2]].values

X

X.shape

y = dataset.iloc[:,1].values

y

y.shape

from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X,y)

model.score(X,y)

model.intercept_

model.coef_

# adjusred rsquared

r2 = model.score(X,y)
n= 84
p = 2

adj_r2 = 1-(1-r2)*(n-1)/(n-p-1)

adj_r2