# -*- coding: utf-8 -*-
"""13_feb_pt2_SKLearn_SAT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19tEBwmzAIIRiPhL8WFoRiTL7eu5qDOI1
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')

dataset = pd.read_csv('sat.csv')

dataset

plt.scatter(dataset['SAT'], dataset['GPA'])
plt.xlabel('SAT----independent')
plt.ylabel('GPA-----dependent')
plt.show()

X = dataset.iloc[:,[0]].values

X

X.shape

y = dataset.iloc[:,1].values

y

y.shape

from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X,y)

model.fit(X,y)

model.score(X,y)

model.intercept_

model.coef_

plt.scatter(dataset['SAT'], dataset['GPA'])
plt.plot(X,model.predict(X), color = 'red')
plt.xlabel('SAT')
plt.ylabel('GPA')
plt.show()