# -*- coding: utf-8 -*-
"""07_Feb_Linear_Regression_statsmodel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mThc7SZAk126R6LlSlAtbUzcN2rSNurn
"""

# for practising we use statsmodels and for the real data we use the library scikit-learn

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")

edu = np.array([1,2,3,4,5])

salary = np.array([200,300,400,500,600])

edu     #independent variable

# residuals = error

salary      #dependent variable

# we are going to make model that predict "salary" from "edu"

plt.scatter(edu,salary)
plt.xlabel("Year of Education------(independent)")
plt.ylabel("Salary -----(dependent)")
plt.show()

import statsmodels.api as sm

x1 = sm.add_constant(edu)

x1

model = sm.OLS(salary,x1).fit()

model.summary()

100+100*3.5

test = np.array([[4.5],[7.0]])

test

test = sm.add_constant(test)

test

model.predict(test)

edu

y_hat = 100+100*edu

y_hat

